version: '3'
services:

  wordpress-php5.4:
    container_name: wordpress-test-php5.4
    image: tfirdaus/wp-docklines:php5.4-fpm
    working_dir: ${WP_PROJECT_DIR}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ../:${WP_PROJECT_DIR}
      - wp-tmp-core:/tmp/wordpress/
      - wp-tmp-tests-dir:/tmp/wordpress-tests-lib

  wordpress-php5.6:
    container_name: wordpress-test-php5.6
    image: tfirdaus/wp-docklines:php5.6-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ../:${WP_PROJECT_DIR}
      - wp-tmp-core:/tmp/wordpress/
      - wp-tmp-tests-dir:/tmp/wordpress-tests-lib

  wordpress-php7.0:
    container_name: wordpress-test-php7.0
    image: tfirdaus/wp-docklines:php7.0-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ../:${WP_PROJECT_DIR}
      - wp-tmp-core:/tmp/wordpress/
      - wp-tmp-tests-dir:/tmp/wordpress-tests-lib

  wordpress-php7.1:
    container_name: wordpress-test-php7.1
    image: tfirdaus/wp-docklines:php7.1-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ../:${WP_PROJECT_DIR}
      - wp-tmp-core:/tmp/wordpress/
      - wp-tmp-tests-dir:/tmp/wordpress-tests-lib

  wordpress-default:
    container_name: wordpress-test-php7.2
    image: tfirdaus/wp-docklines:php7.2-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ../:${WP_PROJECT_DIR}
      - wp-tmp-core:/tmp/wordpress/
      - wp-tmp-tests-dir:/tmp/wordpress-tests-lib

  database:
    image: mysql:5.5
    container_name: mysql-test-database
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

# Cache the database.
volumes:
  mysql:
  wp-dir:
  wp-tmp-core:
  wp-tmp-tests-dir:
